config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    confirmations: "users/confirmations"
  }
  get "user/sign_up", to: "users/registrations#new"

  get "dashboards/index"
  shallow do
    resources :users do
      member do
        patch "promote"
        patch "demote"
      end
    end
    resources :invitations, only: [ :index, :new, :create, :destroy ]
    resources :categories
    resources :items do
      collection do
        get "tom_search"
      end
    end
    resources :receipts do
      resources :items
    end
    resources :shops
    resources :roles
    resources :teams do
      collection do
        post "change"
      end
      resources :memberships do
        member do
          patch "promote"
          patch "demote"
        end
      end
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboards#index"
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :team
  belongs_to :user
  belongs_to :role

  has_many :invitations, dependent: :destroy
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: %i[ show edit update destroy promote demote ]
  before_action :set_team, only: %i[ index ]

  # GET /memberships or /memberships.json
  def index
    authorize(@team)
  end

  # GET /memberships/1 or /memberships/1.json
  def show
    authorize(Membership)
  end

  # GET /memberships/new
  def new
    authorize(Membership)
    @membership = Membership.new
  end

  # GET /memberships/1/edit
  def edit
    authorize(@membership)
  end

  # POST /memberships or /memberships.json
  def create
    authorize(Membership)
    @membership = Membership.new(membership_params)

    respond_to do |format|
      if @membership.save
        format.html { redirect_to @membership, notice: "Membership was successfully created." }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1 or /memberships/1.json
  def update
    authorize(@membership)
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to @membership, notice: "Membership was successfully updated." }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1 or /memberships/1.json
  def destroy
    authorize(@membership)
    @membership.destroy!

    respond_to do |format|
      format.html { redirect_to memberships_path, status: :see_other, notice: "Membership was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def promote
    authorize(@membership)
    @membership.update(role: Role.find(1))
    render turbo_stream: turbo_stream.update(
      "memberships", partial: "memberships/memberships", locals: { team: @membership.team }
    )
  end

  def demote
    authorize(@membership)
    @membership.update(role: Role.find(2))
    render turbo_stream: turbo_stream.update(
      "memberships", partial: "memberships/memberships", locals: { team: @membership.team }
    )
  end

  private
    def set_team
      @team = Team.find(params.expect(:team_id))
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = Membership.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def membership_params
      params.expect(membership: [ :team_id, :user_id, :role_id ])
    end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_with(model: membership, class: "contents") do |form| %>
  <% if membership.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul class="list-disc ml-6">
        <% membership.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :team_id %>
    <%= form.text_field :team_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": membership.errors[:team_id].none?, "border-red-400 focus:outline-red-600": membership.errors[:team_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": membership.errors[:user_id].none?, "border-red-400 focus:outline-red-600": membership.errors[:user_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :role_id %>
    <%= form.text_field :role_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": membership.errors[:role_id].none?, "border-red-400 focus:outline-red-600": membership.errors[:role_id].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/memberships/_membership.html.erb
<tr id="<%= dom_id(membership) %>" class="hover:bg-teal-200">
  <td class="px-2 py-2">
    <%= membership.id %>
  </td>
  <td class="px-2 py-2">
    <%= membership.user.email %>
  </td>
  <td class="px-2 py-2">
    <%= membership.role.name %>
  </td>
  <td>
    <% if current_user.admin? || current_user.superadmin? %>
      <% if membership.role.id == 1 %>
        <%  if current_user.superadmin? %>
          <%=  link_to "Demote",
                       demote_membership_path(membership), data: { turbo_method: :patch },
                       class: "p-2 bg-red-400 text-black border rounded-lg hover:bg-red-200 hover:shadow-lg"
           %>
        <%  end %>
      <%  else %>
        <%=  link_to "Promote",
                      promote_membership_path(membership), data: { turbo_method: :patch },
                      class: "p-2 bg-red-400 text-black border rounded-lg hover:bg-red-200 hover:shadow-lg"
        %>
      <%  end %>
    <% end %>
  </td>
</tr>

app/views/memberships/_memberships.html.erb
<table class="border-collapse border border-gray-400">
  <thead>
  <tr>
    <th class="px-4 py-2 bg-orange-500 border border-gray-500">ID</th>
    <th class="px-4 py-2 bg-orange-500 border border-gray-500">E-Mail</th>
    <th class="px-4 py-2  bg-orange-500 border border-gray-500">Role</th>
    <th class="px-4 py-2  bg-orange-500 border border-gray-500"></th>
  </tr>
  </thead>
  <tbody>
  <% team.memberships_orderd_by_roles.each do |membership| %>
    <%= render partial: "memberships/membership", locals: { membership: membership } %>
  <% end %>
  </tbody>
</table>

app/views/memberships/edit.html.erb
<% content_for :title, "Editing membership" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing membership</h1>

  <%= render "form", membership: @membership %>

  <%= link_to "Show this membership", @membership, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to memberships", memberships_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/memberships/index.html.erb
<h1 class="text-4xl"><%= @team.name %></h1>
<turbo-frame id="memberships">
  <%= render partial: "memberships/memberships", locals: { team: @team } %>
</turbo-frame>
<div class="my-4">
  <%= link_to "Back to teams", teams_path, class: "text-center rounded-lg px-3.5 py-2.5 bg-sky-500 hover:bg-sky-200 hover:text-black inline-block font-medium" %>
</div>

app/views/memberships/new.html.erb
<% content_for :title, "New membership" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New membership</h1>

  <%= render "form", membership: @membership %>

  <%= link_to "Back to memberships", memberships_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/memberships/show.html.erb
<% content_for :title, "Showing membership" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing membership</h1>

  <%= render @membership %>

  <%= link_to "Edit this membership", edit_membership_path(@membership), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to memberships", memberships_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this membership", @membership, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>