config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    confirmations: "users/confirmations"
  }
  get "user/sign_up", to: "users/registrations#new"

  get "dashboards/index"
  shallow do
    resources :users do
      member do
        patch "promote"
        patch "demote"
      end
    end
    resources :invitations, only: [ :index, :new, :create, :destroy ]
    resources :categories
    resources :items do
      collection do
        get "tom_search"
      end
    end
    resources :receipts do
      resources :items
    end
    resources :shops
    resources :roles
    resources :teams do
      collection do
        post "change"
      end
      resources :memberships do
        member do
          patch "promote"
          patch "demote"
        end
      end
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboards#index"
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :team
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: %i[ show edit update destroy ]

  # GET /shops or /shops.json
  def index
    authorize(Shop)
    @shops = policy_scope(Shop)
  end

  # GET /shops/1 or /shops/1.json
  def show
    authorize(Shop)
  end

  # GET /shops/new
  def new
    authorize(Shop)
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
    authorize(@shop)
  end

  # POST /shops or /shops.json
  def create
    authorize(Shop)
    @shop = Shop.new(shop_params.merge(team: current_user.team))

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: "Shop was successfully created." }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1 or /shops/1.json
  def update
    authorize(@shop)
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: "Shop was successfully updated." }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1 or /shops/1.json
  def destroy
    authorize(@shop)
    @shop.destroy!

    respond_to do |format|
      format.html { redirect_to shops_path, status: :see_other, notice: "Shop was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def shop_params
      params.expect(shop: [ :name ])
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= form_with(model: shop, class: "contents") do |form| %>
  <% if shop.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul class="list-disc ml-6">
        <% shop.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": shop.errors[:name].none?, "border-red-400 focus:outline-red-600": shop.errors[:name].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/shops/_shop.html.erb
<div id="<%= dom_id shop %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Name:</strong>
    <%= shop.name %>
  </div>
</div>

app/views/shops/edit.html.erb
<% content_for :title, "Editing shop" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing shop</h1>

  <%= render "form", shop: @shop %>

  <%= link_to "Show this shop", @shop, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to shops", shops_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/shops/index.html.erb
<% content_for :title, "Shops" %>

<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Shops</h1>
    <%= link_to "New shop", new_shop_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="shops" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @shops.any? %>
      <% @shops.each do |shop| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render shop %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", shop, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_shop_path(shop), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", shop, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No shops found.</p>
    <% end %>
  </div>
</div>

app/views/shops/new.html.erb
<% content_for :title, "New shop" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New shop</h1>

  <%= render "form", shop: @shop %>

  <%= link_to "Back to shops", shops_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/shops/show.html.erb
<% content_for :title, "Showing shop" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing shop</h1>

  <%= render @shop %>

  <%= link_to "Edit this shop", edit_shop_path(@shop), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to shops", shops_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this shop", @shop, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>