config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    confirmations: "users/confirmations"
  }
  get "user/sign_up", to: "users/registrations#new"

  get "dashboards/index"
  shallow do
    resources :users do
      member do
        patch "promote"
        patch "demote"
      end
    end
    resources :invitations, only: [ :index, :new, :create, :destroy ]
    resources :categories
    resources :items do
      collection do
        get "tom_search"
      end
    end
    resources :receipts do
      resources :items
    end
    resources :shops
    resources :roles
    resources :teams do
      collection do
        post "change"
      end
      resources :memberships do
        member do
          patch "promote"
          patch "demote"
        end
      end
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboards#index"
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  has_one_attached :bon
  belongs_to :shop
  belongs_to :team
  has_many :items, dependent: :destroy

  validates :shopped_at, presence: true

  def total
    items.sum(&:total) || 0.00
  end
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  before_action :set_receipt, only: %i[ show edit update destroy ]

  # GET /receipts or /receipts.json
  def index
    authorize(Receipt)
    @receipts = policy_scope(Receipt).order(shopped_at: :desc)
  end

  # GET /receipts/1 or /receipts/1.json
  def show
    authorize(Receipt)
  end

  # GET /receipts/new
  def new
    authorize(Receipt)
    @receipt = Receipt.new
  end

  # GET /receipts/1/edit
  def edit
    authorize(@receipt)
  end

  # POST /receipts or /receipts.json
  def create
    authorize(Receipt)
    @receipt = Receipt.new(receipt_params.merge(team: current_user.team))

    respond_to do |format|
      if @receipt.save
        format.html { redirect_to receipt_items_path(@receipt), notice: "Receipt was successfully created." }
        format.json { render :show, status: :created, location: @receipt }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receipts/1 or /receipts/1.json
  def update
    authorize(@receipt)
    respond_to do |format|
      if @receipt.update(receipt_params)
        format.html { redirect_to receipt_items_path(@receipt), notice: "Receipt was successfully updated." }
        format.json { render :show, status: :ok, location: @receipt }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receipts/1 or /receipts/1.json
  def destroy
    authorize(@receipt)
    @receipt.destroy!

    respond_to do |format|
      format.html { redirect_to receipts_path, status: :see_other, notice: "Receipt was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receipt
      @receipt = Receipt.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def receipt_params
      params.expect(receipt: [ :shopped_at, :shop_id, :bon ])
    end
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/views/receipts/_form.html.erb
<%= form_with(model: receipt, class: "contents") do |form| %>
  <% if receipt.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(receipt.errors.count, "error") %> prohibited this receipt from being saved:</h2>

      <ul class="list-disc ml-6">
        <% receipt.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :shop_id %>
    <%= form.collection_select :shop_id, current_user.team.shops.order(name: :asc), :id, :name, {}, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": receipt.errors[:shop_id].none?, "border-red-400 focus:outline-red-600": receipt.errors[:shop_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :shopped_at %>
    <%= form.date_field :shopped_at, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": receipt.errors[:shopped_at].none?, "border-red-400 focus:outline-red-600": receipt.errors[:shopped_at].any?}] %>
  </div>

<!--  <div class="my-5">-->
    <%#= form.label :bon %>
    <%#= form.hidden_field :bon, value: receipt.bon if receipt.bon.attached? %>
    <%#= form.file_field :bon, direct_upload: true, class: "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full" %>
<!--  </div>-->

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/receipts/_receipt.html.erb
<tr class="hover:bg-slate-50">
  <td class="p-4">
    <%= receipt.shopped_at %>
  </td>
  <td class="p-4">
    <%= receipt.shop.name %>
  </td>
  <td class="p-4">
    <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
      <%= link_to "Edit items", receipt_items_path(receipt), class: "text-sm font-semibold" %>
      <%= link_to "Show", receipt, class: "text-sm font-semibold" %>
      <%= link_to "Edit", edit_receipt_path(receipt), class: "text-sm font-semibold" %>
      <%= link_to "Destroy", receipt, class: "text-sm font-semibold", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
    </div>
  </td>
</tr>

app/views/receipts/edit.html.erb
<% content_for :title, "Editing receipt" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing receipt</h1>

  <%= render "form", receipt: @receipt %>

  <%= link_to "Show this receipt", @receipt, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to receipts", receipts_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/receipts/index.html.erb
<% content_for :title, "Kassenbons" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Kassenbons</h1>
    <%= link_to "New receipt", new_receipt_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="receipts" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @receipts.any? %>
      <div class="relative flex flex-col w-full h-full overflow-auto text-gray-700 bg-white shadow-md rounded-lg bg-clip-border">
        <table class="w-full text-left table-auto min-w-max text-slate-800">
          <thead>
          <tr>
            <th class="p-4">Einkaufsdatum</th>
            <th class="p-4">Geschäft</th>
            <th class="p-4"></th>
          </tr>
          </thead>
          <tbody>
            <% @receipts.each do |receipt| %>
              <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
                <%= render receipt %>
              </div>
            <% end %>
          </tbody>
        </table>
      </div>
    <% else %>
      <p class="text-center my-10">No receipts found.</p>
    <% end %>
  </div>
</div>

app/views/receipts/new.html.erb
<% content_for :title, "New receipt" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New receipt</h1>

  <%= render "form", receipt: @receipt %>

  <%= link_to "Back to receipts", receipts_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/receipts/show.html.erb
<% content_for :title, "Showing receipt" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing receipt</h1>

  <%= render @receipt %>

  <%= link_to "Edit items", receipt_items_path(@receipt), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Edit this receipt", edit_receipt_path(@receipt), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to receipts", receipts_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this receipt", @receipt, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>